### PR TITLE
server-info.js

### PR DESCRIPTION
**Pull request by Muffin-Best**
This command give information about server

### CODE REVIEW

**Comment by Microwave-6443** [comment]
theres a lot of misspells, also why it the command named "user-info" if it gives info about the server?

**Comment by Microwave-6443** [comment]
also please translate everything to English thanks

**Comment by Muffin-Best** [comment]
AutoSpell sorry And Okey I translate all to english

**Review by Muffin-Best — COMMENTED** [review]
done

**Comment by Microwave-6443** [comment]
shouldve said this earlier, if you could format the code better so people can actually read it (no offense) that would be appreciated :)

**Review by Muffin-Best — COMMENTED** [review]
successfully code formated

**Pull request merged**
