### PR TITLE
Adding commands

### PR DESCRIPTION
**Pull request by SB-Deco**
Added:
amogus => amogus command, work with mention too
weather <country name> => gives info about the weather in the provided country 
Updated:
meme command is now more advanced

### CODE REVIEW

**Comment by Microwave-6443** [comment]
waiting for sneaky to approve this i guess

**Comment by Microwave-6443** [comment]
this looks like it has an economy but i dont see the economy commands?

**Comment by Microwave-6443** [comment]
we cant accept this pr... please double check your code in `meme.js`

**Comment by SneakyHub** [comment]
Closing due to inactivity and conflicts with existing commands,

**Pull request closed without merging**
