### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Jarvis6969**

### CODE REVIEW

**Comment by Jarvis6969** [comment]
The Message Tracking System you asked for.

**Comment by Microwave-6443** [comment]
we already track messages?

**Comment by TheUsual10k** [comment]
Invite Tracking 🤦‍♂️

**Comment by Microwave-6443** [comment]
and how exactly does a message tracker track invites?

**Comment by TheUsual10k** [comment]
> and how exactly does a message tracker track invites?

I was saying it should've been a InviteTracker , and he Misread it as a Message Tracker or smth?.

**Comment by Microwave-6443** [comment]
> > and how exactly does a message tracker track invites?
> 
> I was saying it should've been a InviteTracker , and he Misread it as a Message Tracker or smth?.

but this code doesnt track invites? it tracks messages

**Comment by SneakyHub** [comment]
Closing due to inactivity and conflicts with existing files,

**Pull request closed without merging**
