### PR TITLE
A few tweaks

### PR DESCRIPTION
**Pull request by DallasOnBackup**
- Fixed a bug in Args management in snipe.js
- Added Author icon to snipes in editsnipe.js

### CODE REVIEW

**Comment by Microwave-6443** [comment]
there is no bug in snipe.js

**Comment by Microwave-6443** [comment]
anyways it looks good

**Comment by DallasOnBackup** [comment]
> there is no bug in snipe.js

It seemed the args parser had a bug in it, so i rewrote it. If not i still reduced the file size by using a different parsing system

**Comment by Microwave-6443** [comment]
> > there is no bug in snipe.js
> 
> It seemed the args parser had a bug in it, so i rewrote it. If not i still reduced the file size by using a different parsing system

alright

**Comment by SneakyHub** [comment]
Great work. 👍

**Pull request merged**
